### ISSUE TITLE
Issue with rule nanopolish_index

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [a-slide/pycoSnake#50]
Hi,
We are trying to get this going and I run into the following error.

WorkflowError in line 147 of XXXXX/pycoMeth/lib/python3.6/site-packages/NanoSnake/workflows/DNA/snakefile.py:
Function did not return str or list of str

Any ideas? Thanks for putting it up.

snakemake --version
5.11.2
NanoSnake v0.0.1.6

**Comment by BenjaminSchwessinger** [comment]
I think the problem is that your conda version of NanoSnake is outdated and the dependency versions are not consistent with your setup.py file

e.g.
install_requires = [
        'pandas==0.24.1',
        'snakemake==5.5.4',
        "loguru==0.3.2",
        "ftputil==3.4"]

Trying to install NanoSnake from the git repository generated a bunch of conflicts with pycometh e.g. pandas. Not sure how to fix this all. Any help appreciated.

**Comment by a-slide** [comment]
Hi @BenjaminSchwessinger ,
Yes it could be a conda version issue. I have quite a few things on my plate this week but I will try to have a look as soon as possible.
Thanks

**Comment by a-slide** [comment]
Hi @BenjaminSchwessinger,

So it turns out updating the snakemake version breaks quite a few things, which is why I initially fixed all the dependencies to a set of versions I know are working together.
I would advise to try to follow the installation tutorial  and create a fresh virtual environment in which to deploy the package:

`conda create -n nanosnake -c aleg -c anaconda -c bioconda -c conda-forge python=3.6 nanosnake`

This will install the appropriate version of snakemake, but not the last one unfortunately.
